set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'Haml'
Plugin 'Jasmine-snippets-for-snipMate'
Plugin 'JavaScript-syntax'
Plugin 'Markdown'
Plugin 'Markdown-syntax'
Plugin 'Puppet-Syntax-Highlighting'
Plugin 'RubySinatra'
Plugin 'Vim-Rspec'
Plugin 'chef.vim'
Plugin 'cocoa.vim'
Plugin 'flymaker'
Plugin 'ftpluginruby.vim'
Plugin 'perl.vim'
Plugin 'rails.vim'
Plugin 'ruby.vim'
Plugin 'vim-addon-ruby-debug-ide'
Plugin 'vim-coffee-script'
Plugin 'xml.vim'
" Plugin 'pangloss/vim-javascript'

" From GitHub
Plugin 'Shougo/neocomplcache.vim'
" Lua needed
" Plugin 'Shougo/neocomplete.vim'
Plugin 'Shougo/neosnippet.vim'
Plugin 'Shougo/neosnippet-snippets'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'Rip-Rip/clang_complete'
Plugin 'docunext/closetag.vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
Plugin 'slim-template/vim-slim'
Plugin 'tomtom/tlib_vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" =================================================
" Editor
" =================================================

" set regexpengine=1
colorscheme Tomorrow-Night
filetype plugin indent on
retab
set autoindent
set bs=indent,eol,start
set cmdheight=1
set expandtab
set laststatus=1
set list
set listchars=tab:>_,trail:\.,nbsp:%,eol:\$
set notitle
set number
set ruler
set shiftwidth=2
set showcmd
set showmatch
set smartindent
set t_Co=256
set tabstop=2
set title
syntax enable

" =================================================
" autocmd
" =================================================

" Close XML tags
autocmd FileType html,erb,php,xml,xslt let b:closetag_html_style=1
autocmd FileType html,erb,php,xml,xslt source ~/.vim/bundle/closetag/plugin/closetag.vim

" Highlight status line on edit mode
augroup InsertHook
  autocmd!
  autocmd InsertEnter * highlight StatusLine guifg=#ccdc90 guibg=#2E4340
  autocmd InsertLeave * highlight StatusLine guifg=#2E4340 guibg=#ccdc90
augroup END

" Remove all trailing spaces on save
autocmd BufWritePre * :%s/\s\+$//e

" =================================================
" Highlight
" =================================================

highlight LineNr     ctermfg=darkyellow
highlight NonText    ctermfg=darkblue   ctermbg=NONE guibg=darkgray
highlight Folded     ctermfg=blue
highlight SpecialKey ctermfg=darkgray   ctermbg=NONE
highlight Pmenu      ctermbg=lightgray  ctermfg=23
highlight PmenuSel   ctermbg=black      ctermfg=yellow
highlight PmenuSbar  ctermbg=yellow
" Zenkaku Space
highlight ZenkakuSpace cterm=underline ctermfg=darkgray ctermbg=NONE
match ZenkakuSpace /　/
" Hankaku Space
"highlight HankakuSpace cterm=underline ctermfg=darkgray ctermbg=NONE
"match HankakuSpace /\s/

" =================================================
" NeoComplCache
" =================================================

let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_enable_smart_case = 1
let g:neocomplcache_min_syntax_length = 3
let g:neocomplcache_lock_buffer_name_pattern = '\*ku\*'

