UNAME=$(uname -s)
DOTFILES=$HOME/dotfiles
source $DOTFILES/env.sh
#
# ohmyzsh
#
export ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$DOTFILES/rc.d/zsh/custom
ZSH_THEME="ngs"
if [ $UNAME = 'Darwin' ]; then
  fpath=($(brew --prefix)/share/zsh/site-functions $fpath)
  plugins=(git rbenv macos docker)
else
  fpath=(~/.zsh/completion $fpath)
  plugins=(git rbenv docker)
fi
source $ZSH/oh-my-zsh.sh
autoload -U compinit
compinit -u
#
# zaw
#
## http://shibayu36.hatenablog.com/entry/20120130/1327937835
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':chpwd:*' recent-dirs-max 5000
zstyle ':chpwd:*' recent-dirs-default yes
zstyle ':completion:*' recent-dirs-insert both
#
source $DOTFILES/rc.d/zsh/zaw/zaw.zsh
#
zstyle ':filter-select' case-insensitive yes
bindkey '^@' zaw-cdr

eval "$(direnv hook zsh)"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true

function gam() { "/Users/ngs/bin/gam/gam" "$@" ; }
