ln -s dotfiles/gitconfig  .gitconfig
ln -s dotfiles/inputrc    .inputrc
ln -s dotfiles/proverc    .proverc
ln -s dotfiles/screenrc   .screenrc
ln -s dotfiles/tmux.conf  .tmux.conf
ln -s dotfiles/vim        .vim
ln -s dotfiles/lynx.cfg   .lynx.cfg
ln -s dotfiles/my.cnf     .my.cnf
ln -s .vim/vimrc          .vimrc
ln -s dotfiles/jsdoc.conf .jsdoc.conf
ln -s dotfiles/mm.cfg     mm.cfg
ln -s dotfiles/module-starter .module-starter
ln -s dotfiles/subversion-config .subversion/config
ln -s dotfiles/tm_properties .tm_properties
ln -s dotfiles/ssh_config .ssh/config
ln -s dotfiles/rspec .rspec
ln -s dotfiles/gitignore .gitignore
ln -s dotfiles/gemrc .gemrc
