syntax on

set t_Co=256
colorscheme Tomorrow-Night
let g:NeoComplCache_EnableAtStartup = 1
let g:closetag_html_style=1
au Filetype html,xml,xsl,mxml,kon,tt,tt2 source ~/.vim/macros/closetag.vim
set notitle
set autoindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2

set nocompatible
set number
set ruler

filetype on
filetype plugin on

set list
set listchars=tab:>_,trail:\.,nbsp:%,eol:\$
set bs=indent,eol,start

set laststatus=1
set cmdheight=1
set showcmd
set title

set showmatch

highlight LineNr ctermfg=darkyellow
highlight NonText ctermfg=darkblue ctermbg=NONE guibg=darkgray
highlight Folded ctermfg=blue
highlight SpecialKey ctermfg=darkgray ctermbg=NONE
highlight Pmenu ctermbg=lightgray ctermfg=magenta
highlight PmenuSel ctermbg=magenta ctermfg=white
highlight PmenuSbar ctermbg=darkblue

highlight ZenkakuSpace cterm=underline ctermfg=darkgray ctermbg=NONE
match ZenkakuSpace /　/

"highlight HankakuSpace cterm=underline ctermfg=darkgray ctermbg=NONE
"match HankakuSpace /\s/

augroup InsertHook
    autocmd!
    autocmd InsertEnter * highlight StatusLine guifg=#ccdc90 guibg=#2E4340
    autocmd InsertLeave * highlight StatusLine guifg=#2E4340 guibg=#ccdc90
augroup END

"set bg=dark
