model = "gpt-5.5"
model_reasoning_effort = "xhigh"
approval_policy = "never"
approvals_reviewer = "user"
sandbox_mode = "danger-full-access"

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true

[tui]
status_line = ["model-with-reasoning", "current-dir", "git-branch"]
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[apps.connector_76869538009648d5b282a4bb21c3d157.tools."github.create_pull_request"]
approval_mode = "approve"

[notice]
hide_full_access_warning = true
