# Copyright 2009: Joshua Timberman (joshua@housepub.org)
require 'fileutils'

desc "Install tmproj"
task :install do
  FileUtils.makedirs("#{ENV['HOME']}/bin")
  FileUtils.makedirs("#{ENV['HOME']}/lib")
  FileUtils.install("tmproj.rb", "#{ENV['HOME']}/bin", :mode => 0755)
  FileUtils.install("tmproj.erb", "#{ENV['HOME']}/lib")
end
